### ISSUE TITLE
decode Extrinsic error on Avail chain, but some logic works on polkadot,kusama,westend...

### ISSUE THREAD

**Issue by gtmickey** [leonardocustodio/polkadart#444]
cli config

```yaml
polkadart:
  output_dir: lib/generated # Optional. Sets the directory of generated files. Provided value should be a valid path on your system. Default: lib/generated
  chains: # Dictionary of chains and endpoints
    polkadot: wss://rpc.polkadot.io
    kusama: wss://kusama-rpc.polkadot.io
    avail: wss://goldberg.avail.tools/ws
    westend: wss://westend-rpc.polkadot.io
```

I running a transfer_keep_alive test, and when run avail case, failed with 
```
package:polkadart/apis/author.dart 17:7  AuthorApi.submitExtrinsic

Exception: {code: 1002, message: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x36e7c0 - <unknown>!rust_begin_unwind
    1: 0xef50 - <unknown>!core::panicking::panic_fmt::h6dad0405f48e39e2
    2: 0x2c96a0 - <unknown>!TaggedTransactionQueue_validate_transaction, data: RuntimeApi("Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x36e7c0 - <unknown>!rust_begin_unwind\n    1: 0xef50 - <unknown>!core::panicking::panic_fmt::h6dad0405f48e39e2\n    2: 0x2c96a0 - <unknown>!TaggedTransactionQueue_validate_transaction")}
```

then I try to decode extrinsic

It works on kusama,polkadot,westend but failed on avail, 

this is avail's extrinsic in hex encode

`senderExtrinsic = 4d028400ba264b7c2da1e38e85f2fbff19a75cd21536bdadabf57839f8c9bd2e074dff3f0160f0de260b8bc6876ce32bf1c6a359170fabbc5b8591762d57149fffd50db433d412901c94c609937ab258ecd40011fa8a59fb529756743e1a92b7acf1a14186f5031000060300ca9b88baf306fc2f4e611fe23ce42ed79fdcea035c6c0807014972e8d973e6611300000c3d5d53aa01`
``` dart
// decode with avail Metadata. result: failed
final metaData = await availStateApi.getMetadata();
final input = Input.fromHex(senderExtrinsic);
final dynamic decoded = ExtrinsicsCodec(chainInfo: metaData.chainInfo).decode(input);
print("extrinsic: ${decoded}");  
```
exception:

```

package:polkadart_scale_codec/primitives/enum.dart 94:7    ComplexEnumCodec.decode
package:polkadart_scale_codec/primitives/proxy.dart 44:19  ProxyCodec.decode
package:polkadart_scale_codec/core/scale_codec.dart 15:25  ScaleCodec.decode
package:substrate_metadata/types/extrinsics.dart 40:44     ExtrinsicsCodec.decode
test/avail_test.dart 118:56                                main.<fn>

Invalid enum index: 155.
```

But if I use same senderExtrinsic , even decode with westend's Metadata, it decode success

```
{hash: 3d335f3770180edcfda02c093daa2b18bd90f513543f8e530658dc9a2ad09351, extrinsic_length: 147, version: 4, signature: {address: MapEntry(Id: [186, 38, 75, 124, 45, 161, 227, 142, 133, 242, 251, 255, 25, 167, 92, 210, 21, 54, 189, 173, 171, 245, 120, 57, 248, 201, 189, 46, 7, 77, 255, 63]), signature: MapEntry(Sr25519: [16, 34, 254, 133, 159, 50, 245, 149, 164, 7, 198, 219, 252, 93, 53, 243, 222, 171, 55, 63, 247, 214, 85, 68, 95, 103, 220, 68, 249, 88, 19, 21, 220, 41, 158, 45, 34, 181, 138, 114, 157, 216, 17, 184, 23, 131, 179, 211, 117, 226, 232, 35, 226, 233, 86, 105, 129, 163, 9, 217, 43, 52, 108, 131]), signedExtensions: {era: {period: 64, phase: 15}, nonce: 4, tip: 0}}, calls: MapEntry(Staking: MapEntry(withdraw_unbonded: {num_slashing_spans: 2291911168}))}
```

**Comment by leonardocustodio** [comment]
Thanks for the report, I can take a look and make some tests after work. cc @justkawal

**Comment by gtmickey** [comment]
update:

<img width="1008" alt="image" src="https://github.com/leonardocustodio/polkadart/assets/164289762/11592bce-b111-4b6d-bd51-718a45c3ca9c">

what I call is `  final runtimeCall = availApi.tx.balances.transferKeepAlive(
        dest: multiDest, value: BigInt.from(120000000000000000));
    print('encodedCall: ${runtimeCall.toJson()}');`
    
    transferKeepAlive method,  instead, decode avail's ExtrinsicPayload , method name is  diff from transferKeepAlive

**Comment by leonardocustodio** [comment]
The CLI generates the extrinsics methods using indexes present in the metadata, though I don't think this will help, would you mind delete all generated files and run `polkadart_cli` only with avail chain, remove the others?

**Comment by gtmickey** [comment]
I try delete all generated files and leave only avail in config, then re gen  file with cli, but still same error, method 'transferKeepAlive'  map to 'withdraw_unbonded'

``` yaml
polkadart:
  output_dir: lib/generated
  chains: # Dictionary of chains and endpoints
#    polkadot: wss://rpc.polkadot.io
#    kusama: wss://kusama-rpc.polkadot.io
    avail: wss://goldberg.avail.tools/ws
#    westend: wss://westend-rpc.polkadot.io
```
 the avail project said they had change some header and types,  quote:

`

Hey, our chains have specific custom types because we changed header and other types. You can check how to initialize an instance of polka api here : https://github.com/availproject/avail/blob/main/avail-js/src/chain/index.ts#L20
And you can see a working example here : https://github.com/availproject/avail/blob/main/avail-js/examples/node-examples/src/transfer.ts

You can try with a local node.
`
