### ISSUE TITLE
cli gen code error on manta network with 'type 'Null' is not a subtype of type 'String''

### ISSUE THREAD

**Issue by gtmickey** [leonardocustodio/polkadart#449]
```
type 'Null' is not a subtype of type 'String'
#0      StateApi.getMetadata (package:polkadart/apis/state.dart:152:45)
<asynchronous suspension>
#1      chainProperties (file:///Users/gtmickey/.pub-cache/hosted/pub.dev/polkadart_cli-0.4.2/bin/generate.dart:38:27)
<asynchronous suspension>
#2      main (file:///Users/gtmickey/.pub-cache/hosted/pub.dev/polkadart_cli-0.4.2/bin/generate.dart:73:40)

```
config:

``` yaml
polkadart:
  output_dir: lib/generated
  chains: # Dictionary of chains and endpoints
    polkadot: wss://rpc.polkadot.io
    manta: wss://pacific-rpc.manta.network/ws
```
