### ISSUE TITLE
How to use git url deps on yaml

### ISSUE THREAD

**Issue by gtmickey** [leonardocustodio/polkadart#451]
Because  these pkg are all inside one repo, I fork to my rep and made some  changed, so how to use  git url  as deps?

``` yaml
  polkadart_keyring: ^0.4.3
  polkadart_cli: ^0.4.2
  polkadart: ^0.4.3
```

I want:
``` yaml
dependency_overrides:

  polkadart_keyring:
    git:
      url:xxx
  polkadart_cli:
    git:
      url:xxx
  polkadart:
    git:
      url:xxx
```
