### ISSUE TITLE
[ink_abi]  Decoding output messages from InkAbi class.

### ISSUE THREAD

**Issue by StepanUsynin** [leonardocustodio/polkadart#518]
#### Description

I have deployed a test smart contract that stores a `bool` value and provides two methods:

- `flip`
- `get`

The `get` method returns a `Result<bool, InkPrimitivesLangError>` type.

When calling `decodeMessageOutput` from the `InkAbi` class, I encounter the following error:

```
Error: Invalid enum index: 194.
ComplexEnumCodec.decode (package:polkadart_scale_codec/primitives/enum.dart:94:7)
```

Part of my code

```dart
final abi = InkAbi(test);

final address = _cryptoUtil.publicKey(contractAddres);
final input = abi.encodeMessageInput('0x2f865bd9', []);
final call = encodeCall(address, input);

final result = await _stateApi.call(
  'ContractsApi_call',
  call,
);

return abi.decodeMessageOutput('0x2f865bd9', result);
```

However manually decoding the response using `SCALE Codec` works as expected:

```dart
final codec = CompositeCodec(
  {'Ok': BoolCodec.codec},
);

final decoded = codec.decode(Input.fromBytes(result));
print(decoded); // {Ok: true}
```

#### Environment
```yaml
  polkadart: ^0.6.1
  polkadart_cli: ^0.6.1
  polkadart_keyring: ^0.6.1
  substrate_bip39: ^0.6.1
  sr25519: ^0.6.1
  polkadart_scale_codec: ^1.4.1
  ss58: ^1.3.1
  ink_abi: ^0.2.1
```

[my_contract.json](https://github.com/user-attachments/files/18638891/my_contract.json)

#### P.S
@leonardocustodio I remember you mentioned that the libraries are still in development, but I will periodically create issues if I find anything, just in case)

This could be a bug or a misconfiguration on my side. Please let me know if additional details are needed. Thank you!

**Comment by leonardocustodio** [comment]
@StepanUsynin yep feel free to create the issues, the goal is to have everything ready by this week. cc @justkawal

**Comment by justkawal** [comment]
@StepanUsynin I've fixed few things according to above issue.

Please lemme know if the issue still persists by fixes in the generator examples from: #509

**Comment by StepanUsynin** [comment]
@justkawal I noticed that you released an update, but unfortunately, I'm still encountering the previously mentioned error.

Additionally, I'm getting a string conversion error when trying to call the name, symbol, and description methods.

However, when calling the total_supply method, which returns a BigInt, everything works correctly.

Here's my code:

```dart
class ContractApi implements IContractApi {
  ContractApi({required StateApi stateApi, required ISubstrateChainApi chainApi})
      : _stateApi = stateApi,
        _chainApi = chainApi;

  final StateApi _stateApi;
  final ISubstrateChainApi _chainApi;

  @override
  Future<String> getTokenName(Contract contract) => _stateCall<String>(
        contract: contract,
        selector: '0x3adaf70d',
        codec: StrCodec.codec,
      );

  @override
  Future<String> getTokenSymbol(Contract contract) => _stateCall<String>(
        contract: contract,
        selector: '0x9bd1933e',
        codec: StrCodec.codec,
      );

  @override
  Future<String> getTokenDescription(Contract contract) => _stateCall<String>(
        contract: contract,
        selector: '0x92e5a00d',
        codec: StrCodec.codec,
      );

  @override
  Future getTokenIcon(Contract contract) => _stateCall<String>(
        contract: contract,
        selector: '0x834b37a8',
        codec: StrCodec.codec,
      );

  @override
  Future<BigInt> getTotalSupply(Contract contract) => _stateCall<BigInt>(
        contract: contract,
        selector: '0xdb6375a8',
        codec: U128Codec.codec,
      );

  @override
  Future<BigInt> getTokenBalance({
    required List<int> owner,
    required Contract contract,
  }) async =>
      BigInt.zero;

  Future<T> _stateCall<T>({
    required Contract contract,
    required String selector,
    required Codec<dynamic> codec,
    List<dynamic> args = const [],
  }) async {
    try {
      final abi = InkAbi(contract.abi);
      final input = abi.encodeMessageInput(selector, args);
      final data = encodeCall(contract.address, input);
      final blocHash = await _chainApi.getBlocHash();

      final result = await _stateApi.call('ContractsApi_call', data,
          at: Uint8List.fromList(hex.decode(blocHash)));

      final compositeCodec = CompositeCodec({'Ok': codec});
      final resultDecode = compositeCodec.decode(Input.fromBytes(result));

      return resultDecode['Ok'] as T;
    } catch (e) {
      print(e);
      rethrow;
    }
  }
}
```

String encoding
<img width="415" alt="Image" src="https://github.com/user-attachments/assets/8877e66e-b219-46f3-a062-f4f912c8977c" />

BigInt encoding
<img width="581" alt="Image" src="https://github.com/user-attachments/assets/32f1b676-6e6d-4aef-a25f-b9670b69b805" />

**Comment by StepanUsynin** [comment]
A small update: I followed all the examples and generated the `Contract` class based on my ABI. However, I'm getting errors when trying to call methods that return a `String`:

```
FormatException (FormatException: Unexpected extension byte (at offset 1))
```

### `pubspec.yaml`
```yaml
name: polkadart_sandbox
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  polkadart: ^0.6.1
  polkadart_cli: ^0.6.1
  polkadart_keyring: ^0.6.1
  substrate_bip39: ^0.6.1
  sr25519: ^0.6.1
  polkadart_scale_codec: ^1.4.1
  ss58: ^1.3.1

  ink_cli:
    git:
      url: https://github.com/leonardocustodio/polkadart.git
      ref: 'main'
      path: 'packages/ink_cli'

  substrate_metadata: ^1.4.1

dependency_overrides:
  ink_abi:
    git:
      url: https://github.com/leonardocustodio/polkadart.git
      ref: 'main'
      path: 'packages/ink_abi'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: any

```
